export const enum ROUTES_ENUM {
  Dashboard = "",
  Info = "info",
  Profile = "profile",
  Admin = "admin",
  Login = "login",
  ContactList = "contacts",
  CouncilMeetingGuide = "council-meeting-guide",
  CouncilMeetings = "council-meetings",
  ContactListOld = "contact-list",
  MarkdownViewer = "view",
  CouncilToolkit = "council-toolkit",
  CommunityCalendar = "community-calendar",
  MailtoGenerator = "mailto",
  Resources = "Resources",
  CityFOIA = "city-foia",
  SignupToSpeak = "signup-to-speak-to-council",
  AgendaPublished = "agenda-info",
  AgendaManagement = "meeting-agenda-management",
  AgendaForm = "meeting-agenda-form",
  AgendaDetails = "meeting-agenda-details",
  AgendaItemForm = "agenda-item-form",
  AgendaItemDetails = "agenda-item-details",
}
