export const enum ROUTES_ENUM {
  Dashboard = "",
  Info = "info",
  Profile = "profile",
  Admin = "admin",
  Login = "login",
  ContactList = "contacts",
  CouncilMeetings = "council-meetings",
  ContactListOld = "contact-list",
  DocumentArchive = "document-archive",
  Rules = "rules",
  Document = "document",
  MarkdownViewer = "view",
  CouncilToolkit = "council-toolkit",
  CommunityCalendar = "community-calendar",
  AgendaPublished = "agenda-info",
  AgendaManagement = "meeting-agenda-management",
  AgendaForm = "meeting-agenda-form",
  AgendaDetails = "meeting-agenda-details",
  AgendaItemForm = "agenda-item-form",
  AgendaItemDetails = "agenda-item-details",
}
